on:
  workflow_call:
    inputs:
      KBC_DEVELOPERPORTAL_APP:
        required: true
        type: string
      KBC_DEVELOPERPORTAL_VENDOR:
        required: true
        type: string
      KBC_DEVELOPERPORTAL_USERNAME:
        required: true
        type: string
      DOCKERHUB_USER:
        required: false
        type: string
    outputs:
      app_image_tag:
        value: ${{ jobs.build-python.outputs.app_image_tag }}
      is_semantic_tag:
        value: ${{ jobs.build-python.outputs.is_semantic_tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      app_image_tag: ${{ steps.tag.outputs.app_image_tag }}
      is_semantic_tag: ${{ steps.tag.outputs.is_semantic_tag }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Docker login
      if: ${{ inputs.DOCKERHUB_USER }} and ${{ secrets.DOCKERHUB_TOKEN }}
      run: docker login --username "${{ inputs.DOCKERHUB_USER }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"

    - name: Build image
      run: docker build -t ${{ inputs.KBC_DEVELOPERPORTAL_APP }} .

    - name: Set image tag
      id: tag
      run: |
        TAG="${GITHUB_REF##*/}"
        IS_SEMANTIC_TAG=$(echo "$TAG" | grep -q '^v\?[0-9]\+\.[0-9]\+\.[0-9]\+$' && echo true || echo false)
        echo "Tag = '$TAG', is semantic tag = '$IS_SEMANTIC_TAG'"
        echo "is_semantic_tag=$IS_SEMANTIC_TAG" >> $GITHUB_OUTPUT
        echo "app_image_tag=$TAG" >> $GITHUB_OUTPUT

    - name: Push image to ECR
      if: ${{ inputs.DOCKERHUB_USER }} and ${{ secrets.DOCKERHUB_TOKEN }}
      uses: keboola/action-push-to-ecr@master
      with:
        vendor: ${{ inputs.KBC_DEVELOPERPORTAL_VENDOR }}
        app_id: ${{ inputs.KBC_DEVELOPERPORTAL_APP }}
        username: ${{ inputs.KBC_DEVELOPERPORTAL_USERNAME }}
        password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
        tag: ${{ steps.tag.outputs.app_image_tag }}
        push_latest: ${{ steps.tag.outputs.is_semantic_tag }}
        source_image: ${{ inputs.KBC_DEVELOPERPORTAL_APP }}